package com.duta.movie.model

import androidx.compose.runtime.Immutable
import kotlinx.serialization.Serializable

@Serializable
@Immutable
data class Subtitle(
    val label: String,
    val url: String,
    val language: String,
    val isAutoGenerated: Boolean = false,
    val localUri: String? = null
)
