package com.duta.movie.util

/**
 * Supabase configuration for global persistent comments across all app installations.
 * 
 * Instructions:
 * 1. Log in to https://supabase.com (free account).
 * 2. Create a new project (e.g. "dreamstream-comments").
 * 3. Go to Project Settings -> API.
 * 4. Copy "Project URL" into PROJECT_URL below.
 * 5. Copy "Project API Keys -> anon (public)" into ANON_KEY below.
 * 6. Go to SQL Editor in Supabase and run:
 * 
 *    create table comments (
 *      id bigint generated by default as identity primary key,
 *      video_id text not null,
 *      user_name text not null,
 *      comment text not null,
 *      created_at timestamp with time zone default timezone('utc'::text, now()) not null
 *    );
 * 
 *    alter table comments enable row level security;
 *    create policy "Allow public read" on comments for select using (true);
 *    create policy "Allow public insert" on comments for insert with check (true);
 */
object SupabaseConfig {
    /**
     * Supabase Project URL (e.g. "https://xxxxxxxxxxxxxxxxxxxx.supabase.co")
     */
    const val PROJECT_URL = "https://seyzzmivcppoadgwkjmh.supabase.co"

    /**
     * Supabase public anon key
     */
    const val ANON_KEY = "sb_publishable_iPBPTl_C2BvSq0tub3kQHA_wpEKDsFf"

    val isConfigured: Boolean
        get() = PROJECT_URL.isNotBlank() && ANON_KEY.isNotBlank() && !PROJECT_URL.contains("your-project")
}
